# Generated by Django 2.1.2 on 2020-01-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200105_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=True, to='blog.Images'),
        ),
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Images'),
        ),
    ]
