# Generated by Django 2.1.2 on 2020-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200106_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='html',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='html',
            new_name='content',
        ),
    ]
