# Generated by Django 2.1.2 on 2020-02-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200228_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='background_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
