# Generated by Django 2.1.2 on 2020-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_type_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tag_name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='type',
            name='tag_name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
