# Generated by Django 2.1.2 on 2020-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
