# Generated by Django 2.1.2 on 2020-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200107_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='font_color',
            field=models.CharField(blank=True, default='black', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='font_color',
            field=models.CharField(blank=True, default='black', max_length=100),
        ),
    ]
