# Generated by Django 2.1.2 on 2020-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200321_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(default='#0033cc', max_length=50),
        ),
    ]
