# Generated by Django 2.1.2 on 2020-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200401_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=159),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_description',
            field=models.CharField(blank=True, max_length=159),
        ),
        migrations.AddField(
            model_name='type',
            name='meta_description',
            field=models.CharField(blank=True, max_length=159),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
