# Generated by Django 2.1.2 on 2020-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200401_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_name',
            field=models.CharField(blank=True, max_length=110, unique=True),
        ),
    ]
