# Generated by Django 2.1.2 on 2020-04-01 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_mod',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
